steps:

- name: node
  entrypoint: yarn
  args: ['install']

- name: node
  entrypoint: yarn
  args: ['lint']

- name: node
  entrypoint: yarn
  args: ['test']

- name: node
  entrypoint: yarn
  args: ['build']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['gsutil', 'rsync', '-r', './dist', 'gs://my-awesome-vue-js-application-gcdc-lk']
